version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node:12"
    working_directory: ~/insurello
    steps:
      - checkout
      - run:
          name: Install
          command: "npm install"
      - run:
          name: Build
          command: "npm run validate"
